In [1]:
import pandas as pd
import numpy as np
from sklearn import svm

In [2]:
data=pd.read_csv('C:\\Users\\USER\\Desktop\\hrst\\heart.csv')
data.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [3]:
data.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [4]:
data.describe()

Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.396514   198.799564    0.233115  136.809368   
std      9.432617   18.514154   109.384145    0.423046   25.460334   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.250000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [5]:
data.shape

(918, 12)

In [6]:
from sklearn import preprocessing
ohe=pd.get_dummies(data)
df=ohe

In [7]:
x=df.drop(columns=['HeartDisease'],axis=1)
y=df['HeartDisease']

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [9]:
model=svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.5978260869565217

In [10]:
model=svm.SVC(kernel='rbf',C=20,gamma='auto')
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.5978260869565217

In [11]:
model=svm.SVC(kernel='linear',C=20,gamma='auto')
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.8659420289855072

In [12]:
from sklearn.model_selection import cross_val_score
cross_val_score(svm.SVC(kernel='rbf',C=30,gamma='auto'),x,y,cv=5)

array([0.60869565, 0.57608696, 0.58152174, 0.57923497, 0.56284153])

In [13]:
cross_val_score(svm.SVC(kernel='linear',C=20,gamma='auto'),x,y,cv=5)

array([0.86956522, 0.85869565, 0.84782609, 0.84153005, 0.74863388])

In [14]:
cross_val_score(svm.SVC(kernel='linear',C=30,gamma='auto'),x,y,cv=5)

array([0.88043478, 0.83695652, 0.84782609, 0.84153005, 0.74863388])

In [15]:
kernels=['rbf','linear']
C=[1,20,30]
avg_scores={}
for kval in kernels:
    for cval in C:
        cv_scores=cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),x,y,cv=5)
        avg_scores[kval+'_'+str(cval)]=np.average(cv_scores)
avg_scores

{'rbf_1': 0.5696780708006652,
 'rbf_20': 0.5816761701116655,
 'rbf_30': 0.5816761701116655,
 'linear_1': 0.8299952482775007,
 'linear_20': 0.8332501781895937,
 'linear_30': 0.8310762651461154}

In [16]:
from sklearn.model_selection import GridSearchCV
clf=GridSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,20,30],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)
clf.fit(x,y)
clf.cv_results_

{'mean_fit_time': array([4.94056225e-02, 3.94335885e+00, 4.54986572e-02, 3.24319442e+01,
        6.81113720e-02, 6.86113997e+01]),
 'std_fit_time': array([6.99866627e-03, 8.68538753e-01, 5.19002115e-03, 7.43577183e+00,
        1.51617286e-02, 9.69464428e+00]),
 'mean_score_time': array([0.02414484, 0.        , 0.02645864, 0.01057124, 0.0344523 ,
        0.        ]),
 'std_score_time': array([0.0071328 , 0.        , 0.00629967, 0.00647111, 0.00398023,
        0.        ]),
 'param_C': masked_array(data=[1, 1, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'ker

In [18]:
dataset=pd.DataFrame(clf.cv_results_)
dataset

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.049406      0.006999         0.024145        0.007133       1   
1       3.943359      0.868539         0.000000        0.000000       1   
2       0.045499      0.005190         0.026459        0.006300      20   
3      32.431944      7.435772         0.010571        0.006471      20   
4       0.068111      0.015162         0.034452        0.003980      30   
5      68.611400      9.694644         0.000000        0.000000      30   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.581522   
1       linear   {'C': 1, 'kernel': 'linear'}           0.858696   
2          rbf     {'C': 20, 'kernel': 'rbf'}           0.608696   
3       linear  {'C': 20, 'kernel': 'linear'}           0.869565   
4          rbf     {'C': 30, 'kernel': 'rbf'}           0.608696   
5       linear  {'C': 30, 'kernel': 'linear'}           0.880435   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.581522           0.581522           0.546448           0.557377   
1           0.847826           0.847826           0.852459           0.743169   
2           0.576087           0.581522           0.579235           0.562842   
3           0.858696           0.847826           0.841530           0.748634   
4           0.576087           0.581522           0.579235           0.562842   
5           0.836957           0.847826           0.841530           0.748634   

   mean_test_score  std_test_score  rank_test_score  
0         0.569678        0.014912                6  
1         0.829995        0.043596                3  
2         0.581676        0.014980                4  
3         0.833250        0.043376                1  
4         0.581676        0.014980                4  
5         0.831076        0.043949                2